In [6]:
import pandas as pd



df = pd.read_csv("D:\\Work\\Project_S_models\\notebooks\\recommend\\datasheet.csv")

unwanted_types = [
    "Face Makeup", "Bath and Body", "Other Hair Care", "Shampoo", "Fragrance", 
    "Hand Care", "Condi9oner", "Lip Moisturizer", "Eye Makeup", "tanning", 
    "nan (เสิชละ้ไม่เจอไร)", "Cheek Makeup", "Nail Care", "Lip Mask", 
    "Other", "Other Haircare", "Tool", "False Eyelash"
]

df = df[~df['type'].isin(unwanted_types)]
df

,brand,name,type,country,ingridients,afterUse
0,The Ordinary,Glycolic Acid 7% Toning Solution,Toner,Canada,"Water,Glycolic Acid,Rosa Damascena Flower Wate...","Good For Oily Skin,Skin Texture,Reduces Large ..."
1,La Roche-Posay,Toleriane Hydrating Gentle Face Cleanser,Face Cleanser,France,"Water,Glycerin,Pentaerythrityl Tetraethylhexan...","Good For Oily Skin,Redness Reducing,Reduces Ir..."
2,The Ordinary,Niacinamide 10% + Zinc 1%,Facial Treatment,Canada,"Water,Niacinamide,Pentylene Glycol,Zinc PCA,Di...","Good For Oily Skin,Redness Reducing,Acne Fight..."
3,Youth To The People,Superfood Antioxidant Cleanser,Face Cleanser,United States,"Water,Cocamidopropyl Hydroxysultaine,Sodium Co...","Redness Reducing,Reduces Irritation,Skin Textu..."
4,COSRX,Low pH Good Morning Gel Cleanser,Face Cleanser,South Korea,"Water,Cocamidopropyl Betaine,Sodium Lauroyl Me...","Good For Oily Skin,Reduces Irritation,Reduces ..."
...,...,...,...,...,...,...
19045,CeraVe,Hydrating Facial Cleanser,Face Cleanser,Canada,"Water,Glycerin,Cetearyl Alcohol,Peg-40 Stearat...","Redness Reducing,Anti-Aging,Scar Healing,Brigh..."
19046,Beauty of Joseon,Ginseng Essence Water,Essence,South Korea,"Panax Ginseng Root Water,Butylene Glycol,Glyce...","Good For Oily Skin,Redness Reducing,Reduces Ir..."
19047,CeraVe,PM Facial Moisturizing Lotion,Night Moisturizer,Canada,"Water,Glycerin,Caprylic/Capric Triglyceride,Ni...","Good For Oily Skin,Redness Reducing,Anti-Aging..."
19048,The Ordinary,AHA 30% + BHA 2% Peeling Solution,Facial Treatment,Canada,"Glycolic Acid,Water,Aloe Barbadensis Leaf Wate...","Good For Oily Skin,Reduces Irritation,Skin Tex..."
19049,COSRX,Advanced Snail 96 Mucin Power Essence,Essence,South Korea,"Snail Secretion Filtrate,Betaine,Butylene Glyc...",Redness Reducing

In [7]:
# Update type to 'Pads' if name contains 'Pads' or 'pad' and type is 'Facial Treatment'

newdf = df.copy()

newdf.loc[(newdf['name'].str.contains('Pads', case=False)) & (
    newdf['type'] == 'Facial Treatment'), 'type'] = 'Pads'

# Update type to 'Cream' if name contains 'Cream' and type is one of the specified types
newdf.loc[(newdf['name'].str.contains('Cream', case=False)) &
          (newdf['type'].isin(['Night Moisturizer', 'Day Moisturizer', 'Face Cream', 'General Moisturizer'])), 'type'] = 'Cream'

newdf.loc[(newdf['name'].str.contains('Lotion', case=False)) &
          (newdf['type'].isin(['Night Moisturizer', 'Day Moisturizer', 'Face Cream', 'General Moisturizer'])), 'type'] = 'Lotion'

newdf.loc[(newdf['name'].str.contains('Serum', case=False)) &
          (newdf['type'].isin(['Facial Treatment'])), 'type'] = 'Serum'

newdf.loc[(newdf['name'].str.contains('Serum', case=False)) &
          (newdf['type'].isin(['Facial Treatment'])), 'type'] = 'Serum'

newdf.loc[(newdf['name'].str.contains('Mist', case=False)) &
          (newdf['type'].isin(['Facial Treatment'])), 'type'] = 'Mist'

newdf.loc[(newdf['name'].str.contains('Spray', case=False)) &
          (newdf['type'].isin(['Facial Treatment'])), 'type'] = 'Mist'

newdf.loc[(newdf['name'].str.contains('Gel', case=False)) &
          (newdf['type'].isin(['Facial Treatment'])), 'type'] = 'Gel'

newdf.loc[(newdf['name'].str.contains('Emulsion', case=False)) &
          (newdf['type'].isin(['Emulsion','Facial Treatment'])), 'type'] = 'Emulsion'

newdf.loc[(newdf['name'].str.contains('Facial', case=False)) &
         (newdf['type'].isin(['Oil'])), 'type'] = 'Oil'

newdf.loc[(newdf['name'].str.contains('Face', case=False)) &
         (newdf['type'].isin(['Oil'])), 'type'] = 'Oil'

newdf.loc[(newdf['name'].str.contains('Essence', case=False)) &
          (newdf['type'].isin(['Essence','Facial Treatment'])), 'type'] = 'Essence'

In [8]:
newdf

,brand,name,type,country,ingridients,afterUse
0,The Ordinary,Glycolic Acid 7% Toning Solution,Toner,Canada,"Water,Glycolic Acid,Rosa Damascena Flower Wate...","Good For Oily Skin,Skin Texture,Reduces Large ..."
1,La Roche-Posay,Toleriane Hydrating Gentle Face Cleanser,Face Cleanser,France,"Water,Glycerin,Pentaerythrityl Tetraethylhexan...","Good For Oily Skin,Redness Reducing,Reduces Ir..."
2,The Ordinary,Niacinamide 10% + Zinc 1%,Facial Treatment,Canada,"Water,Niacinamide,Pentylene Glycol,Zinc PCA,Di...","Good For Oily Skin,Redness Reducing,Acne Fight..."
3,Youth To The People,Superfood Antioxidant Cleanser,Face Cleanser,United States,"Water,Cocamidopropyl Hydroxysultaine,Sodium Co...","Redness Reducing,Reduces Irritation,Skin Textu..."
4,COSRX,Low pH Good Morning Gel Cleanser,Face Cleanser,South Korea,"Water,Cocamidopropyl Betaine,Sodium Lauroyl Me...","Good For Oily Skin,Reduces Irritation,Reduces ..."
...,...,...,...,...,...,...
19045,CeraVe,Hydrating Facial Cleanser,Face Cleanser,Canada,"Water,Glycerin,Cetearyl Alcohol,Peg-40 Stearat...","Redness Reducing,Anti-Aging,Scar Healing,Brigh..."
19046,Beauty of Joseon,Ginseng Essence Water,Essence,South Korea,"Panax Ginseng Root Water,Butylene Glycol,Glyce...","Good For Oily Skin,Redness Reducing,Reduces Ir..."
19047,CeraVe,PM Facial Moisturizing Lotion,Lotion,Canada,"Water,Glycerin,Caprylic/Capric Triglyceride,Ni...","Good For Oily Skin,Redness Reducing,Anti-Aging..."
19048,The Ordinary,AHA 30% + BHA 2% Peeling Solution,Facial Treatment,Canada,"Glycolic Acid,Water,Aloe Barbadensis Leaf Wate...","Good For Oily Skin,Reduces Irritation,Skin Tex..."
19049,COSRX,Advanced Snail 96 Mucin Power Essence,Essence,South Korea,"Snail Secretion Filtrate,Betaine,Butylene Glyc...",Redness Reducing

In [9]:
newdf.to_csv(csv_file_path, index=False)